name: Deploy to EC2
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: 'placeholder'

    - name: Set ownership
      run: |
          chown -R $(id -u):$(id -g) $PWD
    - name: Adding Known Hosts
      run: ssh-keyscan -H 147.28.183.119 >> ~/.ssh/known_hosts

    - name: Connect to EC2 instance
      run: ssh root@147.28.183.119 sh /mnt/Update-Frontend-staging.sh
